//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMvccc.Models.DatabaseClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULUPLER
    {
        public int KULUPID { get; set; }
        public string KULUPAD { get; set; }
        public Nullable<short> KULUPKONTENJAN { get; set; }
        public Nullable<bool> Aktifmi { get; set; }
    }
}
